default: &default
  host: localhost
  port: 6379

development:
  <<: *default
  password: <%= ENV.fetch("REDIS_SECRET") { '' } %>

test:
  <<: *default
  host: <%= ENV.fetch("REDIS_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("REDIS_PORT") { '6379' } %>
  password: <%= ENV.fetch("REDIS_SECRET") { '' } %>

production:
  <<: *default
  host: redis
  password: <%= ENV.fetch("REDIS_SECRET") { '' } %>
